# Generated by Django 5.2.8 on 2025-11-05 15:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('WORKED', 'Worked'), ('VACATION', 'Vacation'), ('SICK_LEAVE', 'Sick Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('PUBLIC_HOLIDAY', 'Public Holiday')], default='WORKED', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Number of hours worked', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('12.00'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'user'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_3daa40_idx'), models.Index(fields=['date'], name='attendance__date_19baa0_idx'), models.Index(fields=['type'], name='attendance__type_f86ff2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hours_worked', 0), ('type', 'VACATION')), models.Q(('type', 'VACATION'), _negated=True), _connector='OR'), name='valid_hours_for_vacation'), models.CheckConstraint(condition=models.Q(models.Q(('hours_worked', 0), ('type', 'UNPAID_LEAVE')), models.Q(('type', 'UNPAID_LEAVE'), _negated=True), _connector='OR'), name='valid_hours_for_unpaid_leave'), models.CheckConstraint(condition=models.Q(models.Q(('hours_worked', 0), ('type', 'PUBLIC_HOLIDAY')), models.Q(('type', 'PUBLIC_HOLIDAY'), _negated=True), _connector='OR'), name='valid_hours_for_public_holiday')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('total_vacation_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('total_sick_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('total_unpaid_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('public_holiday_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='payroll.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_attendance_summaries',
                'ordering': ['-period', 'user'],
                'indexes': [models.Index(fields=['user', 'period'], name='monthly_att_user_id_22b48d_idx'), models.Index(fields=['period'], name='monthly_att_period__651d85_idx')],
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('total_days_allocated', models.PositiveSmallIntegerField(default=21, help_text='Total vacation days allocated for the year', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('days_used', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('days_carried_over', models.SmallIntegerField(default=0, help_text='Days carried over from previous year (can be negative)', validators=[django.core.validators.MinValueValidator(-365), django.core.validators.MaxValueValidator(365)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacation_balances',
                'ordering': ['-year', 'user'],
                'indexes': [models.Index(fields=['user', 'year'], name='vacation_ba_user_id_14b432_idx'), models.Index(fields=['year'], name='vacation_ba_year_f97f22_idx')],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
