# Generated by Django 5.2.8 on 2025-11-05 15:37

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MANAGER_CSV', 'CSV aggregated per manager'), ('USER_PDF', 'PDF per employee')], max_length=20)),
                ('file', models.FileField(upload_to=apps.reports.models.report_upload_path)),
                ('file_format', models.CharField(blank=True, help_text='File extension (csv, pdf)', max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='payroll.payrollperiod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_reports', to=settings.AUTH_USER_MODEL)),
                ('users_included', models.ManyToManyField(blank=True, related_name='included_in_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of send attempts')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='reports.generatedreport')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['type', 'period', 'manager'], name='generated_r_type_3ce506_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['type', 'period', 'user'], name='generated_r_type_6d5712_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('type', 'MANAGER_CSV')), fields=('type', 'period', 'manager'), name='unique_manager_report_per_period'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('type', 'USER_PDF')), fields=('type', 'period', 'user'), name='unique_user_report_per_period'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manager__isnull', False), ('type', 'MANAGER_CSV'), ('user__isnull', True)), ('type', 'USER_PDF'), _connector='OR'), name='report_csv_requires_manager'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manager__isnull', True), ('type', 'USER_PDF'), ('user__isnull', False)), ('type', 'MANAGER_CSV'), _connector='OR'), name='report_pdf_requires_employee'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'sent_at'], name='email_logs_status_00c463_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email'], name='email_logs_to_emai_9c46ac_idx'),
        ),
    ]
