# Generated by Django 5.2.8 on 2025-11-05 15:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='RON', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency must be a 3 letters  (e.g., RON, EUR, USD).')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compensations',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='No further edits allowed for this month, if locked')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_periods',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'bonuses',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unpaid_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonuses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslips',
                'ordering': ['-period', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='payroll_period_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['period', 'user'], name='bonuses_period__8b2e11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bonus',
            unique_together={('user', 'period', 'description')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['period', 'user'], name='payslips_period__74ecc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('user', 'period')},
        ),
    ]
